hash-format = "sha256"

[[files]]
file = "mods/additional-rpg-jewelry.pw.toml"
hash = "c72fcf42d3b2ec808836616ab6f1f8bbacfcd328628e1e4525829c056f67d455"
metafile = true

[[files]]
file = "mods/archers.pw.toml"
hash = "3e8dba64a771a4706cc40ea4cd2ebfc8b36899701049ffc8b788313d2bf65afc"
metafile = true

[[files]]
file = "mods/armory-rpg-series.pw.toml"
hash = "e888f216b44cf61638716bd22d15d69429e5e051670ed6b7a7ba9fe14da4c185"
metafile = true

[[files]]
file = "mods/arsenal-rpg-series.pw.toml"
hash = "55692d2809fd7cf0b78804f94b6a6e4b7f80aeee878d1068e229d04ed2d6cfeb"
metafile = true

[[files]]
file = "mods/azurelib-armor.pw.toml"
hash = "07e03d9f220fe28d5ae1b767718e72da8666da6448000f3cc06a80ec4abe42ba"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "ddc951666b9b867b0ff7671865a33f15adb5331f3d7c8bc179e0ec86795e020f"
metafile = true

[[files]]
file = "mods/better-combat.pw.toml"
hash = "b14408056dfdcdbbfe1c41e05de322457d508a611efae462db9a4103eb168887"
metafile = true

[[files]]
file = "mods/bookshelf-lib.pw.toml"
hash = "5f32244bbf7f4864d6570bde7f7223655f52d5df455e7b9fe650b10dee42f830"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "446c173c87b7908daee86b0dee89c6b628c77beb7a0bc091ff5252b7c0062080"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "cde21d14fcaf9495f0f5b3d8fb298dd60cb12badc21a27414c25ebf11dfb3fe1"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "4f97764f3cb4c74f84afbe32cf8a1d2cefecda129c0f1441906562dcb8f2b8cb"
metafile = true

[[files]]
file = "mods/elemental-wizards-rpg.pw.toml"
hash = "5d0e8ccb22d3295ede4401329b6861649c7e92bdf33eda9aa79a9c8207e8e096"
metafile = true

[[files]]
file = "mods/enchantment-descriptions.pw.toml"
hash = "f7bb88ccf59b362d533cef59b28b0cab3ef017ad7462dfbe0daae2a0aa30032e"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "446f8047ee9168b65fe9d4600f82cb915c7aa0d0f049a344177ba340a5b93a8a"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "d7c055f277c1751122d9abc5f09015e629699e04a9383cd0c666b33436293079"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "238b3ceb4214a682480ce00eefae5d34efa299ff6ff667e4b2f2ed503c6e76ee"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "d8cdb69801ff0ffdf8c9cf6834dd592ca79ce1da139d303f8d17a62afec1abe2"
metafile = true

[[files]]
file = "mods/gazebos.pw.toml"
hash = "2af2d62c97cbd353887ea0ee53b0571bdcf1034cb3fbe653274d059db4ee9ed7"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "43419651a1c8ee71281ce6d607fba199f0e87ba41f9725caa65b4dab2e589d49"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "907ed71a8d572d5bc2a8f956b0b0d0fad37e1d5bdd48464041a76ef8fca79cb7"
metafile = true

[[files]]
file = "mods/inventory-management.pw.toml"
hash = "40b85465f985bcb300b89018271103db50340ac99949502fc3ff64fb50bcbbae"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "5284f6d141a990f4ea021c12b851e07102f5cb22743cf7b33be6ad2eb4c8d3f5"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "80858e1b1477432110b72aab33348635139d6e8fe7bc05db3ba00651de635720"
metafile = true

[[files]]
file = "mods/jewelry.pw.toml"
hash = "f4c71bfe1a0712f6bf75c2432f97bdab9b379b9f55ccd451317d0d7c9edc8293"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "9236940eafe8e97819f093c3c77236ee47de3b7f97a17f3fcf31114034962611"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "d917697e84a95f857a447d26f94d93169a5a62176c93193cdf80c8d8bc1e280a"
metafile = true

[[files]]
file = "mods/more-rpg-classes-skill-tree.pw.toml"
hash = "8a663ed4aa1803dbfa961427c18fed7354630a5efecb612eea819cc8113eee40"
metafile = true

[[files]]
file = "mods/more-rpg-library.pw.toml"
hash = "5b6c22073aae016563893938437569ff7980f5b87d0b36e0751d43ee388a7677"
metafile = true

[[files]]
file = "mods/no-hostiles-around-campfire.pw.toml"
hash = "d8fef6507b7903b4373514e21dae1c2ffeea09ec928ca7481397a67b840d39ec"
metafile = true

[[files]]
file = "mods/paladins-and-priests.pw.toml"
hash = "caa5a9677143236b8faeec757d276317f90e217e1b653a5f6a3935d5e58a4324"
metafile = true

[[files]]
file = "mods/pick-up-notifier.pw.toml"
hash = "af6de4e48064926264441ace0dc8f3193deedd534e2963c25a7700d4dfa6f825"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "2e2c1b47b513663871e71c89a699c66ac9fcc97633f007ed064ce4410f220f5a"
metafile = true

[[files]]
file = "mods/playeranimator.pw.toml"
hash = "ae55eda5b79aeb01fd4068cc34051019e34779c2d4748aba86e5dba522b7b61d"
metafile = true

[[files]]
file = "mods/potions-description.pw.toml"
hash = "697c1c2778d7ed7e9029e9477661f1a4c8e1b69e4cf07e13179f51137e5480ff"
metafile = true

[[files]]
file = "mods/prickle.pw.toml"
hash = "122659d423e8fe5c47b4121bf382e5ceea0ea2c644cd0a08d577cf58ef55d495"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "44a6662d6ac604b2173a8bc426a10c0d621c8ba99d37d1b72525c140c42cb358"
metafile = true

[[files]]
file = "mods/ranged-weapon-api.pw.toml"
hash = "1169c6f5f7cd13d01081f996cda2a029809877aff999e9bf4e6b0d44b027aa58"
metafile = true

[[files]]
file = "mods/relics-rpg.pw.toml"
hash = "592f77caab1a27fc9b5dfb102c2cda6c1d41267dd3392367bcea4893a38e9641"
metafile = true

[[files]]
file = "mods/rogues-and-warriors.pw.toml"
hash = "ecc4102c0c890b0798b692118eaefae613d3b08084f08a8a3e827cc25e923456"
metafile = true

[[files]]
file = "mods/runes.pw.toml"
hash = "670cb4987ac4ff766b655d58001022c855a86d84f7f25c8adc28d1cc3c24ac95"
metafile = true

[[files]]
file = "mods/shield-api.pw.toml"
hash = "1554f121bc3ffd5ddc4152f5e8d06227a3dddc583021d36d11237975378e82f1"
metafile = true

[[files]]
file = "mods/skill-tree.pw.toml"
hash = "2ce9354135df1ac59a3f485252f648786cd9512c14e2bd6d046deae8fc6ec9fc"
metafile = true

[[files]]
file = "mods/skills.pw.toml"
hash = "d5619b2564c6dd9b7a55c6f02f8f1da35f0c05c2d0c04f1f18386566b639a62e"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "be0c8881821da897824770b2a71f0f3765a233eda69b295fa5b92ffe8a25014c"
metafile = true

[[files]]
file = "mods/spell-engine.pw.toml"
hash = "36486ffdfa9d483d2510e9e9aad881b111e275dfea9bdc94be5265fa22fa3051"
metafile = true

[[files]]
file = "mods/spell-power.pw.toml"
hash = "580698cb1afc910d403bcd2174554fdad4aac751a149be50a4b1e73c72bd7296"
metafile = true

[[files]]
file = "mods/structure-pool-api.pw.toml"
hash = "919153a4c85c7b33c97ac722d95b001c34903368880b144388c6d20cb77c19dc"
metafile = true

[[files]]
file = "mods/trashslot.pw.toml"
hash = "40c60c458184ab9d15fdcc4c610607eca60a1557bbf484fad2942a803d75e0ec"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
hash = "860812150cb54f0d9ee1bce7b72798b6cc5f752bb05709f0c60231d054ec281d"
metafile = true

[[files]]
file = "mods/visual-workbench.pw.toml"
hash = "37c8746fe9057612cd4f21e1221760e8dd2f78ce6b38a237b0ac925de21541e0"
metafile = true

[[files]]
file = "mods/wizards.pw.toml"
hash = "cdec4d7d3a82b62b46172e78e25d24aab5922293ab355f119a6f86684fa586f1"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "8ffa4ba1466882a5abef6c6d220824f1ce4e228771f854f19e4fceb80598723c"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "fb09f6357ae2e3dcfea36520efde6e9b761efffc63b4dfdec5e4b11011bac58c"
metafile = true

[[files]]
file = "packwiz-installer-bootstrap.jar"
hash = "a8fbb24dc604278e97f4688e82d3d91a318b98efc08d5dbfcbcbcab6443d116c"

[[files]]
file = "packwiz-installer.jar"
hash = "c9f646908d340d84773948a9a7d98bc1dae250d35e1016dc6e2b8459760b5598"
