name = "Ninth House"
author = "Naberius Corax"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "931c92d757951dcc97735535c49d176bfc7ab76d71c108d2a1f478778393acbf"

[versions]
fabric = "0.17.3"
minecraft = "1.21.1"
